version: '2'
services:
#start These services can be disabled without affecting any other services
    cron:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cron
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
    elasticsearch:
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
    beanstalkd:
        volumes:
            - data-beanstalkd:/var/lib/beanstalkd
    redis:
        volumes:
            - data-redis:/data
#end These services can be disabled without affecting any other services
    nginxhttp:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nginxhttp
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        ports:
            - "80:80"
        volumes:
            - acme-challenge:/DLEMP/certbot/public/.well-known/acme-challenge
    certbot:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/certbot
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        depends_on:
            - nginxhttps
        volumes_from:
            - nginxhttp:rw
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
            - var-lib-letsencrypt:/var/lib/letsencrypt
volumes:
    var-lib-mysql:
        driver: local
    elasticsearch-data:
        driver: local
    acme-challenge:
        driver: local
    data-beanstalkd:
        driver: local
    data-redis:
        driver: local
    var-lib-letsencrypt:
        driver: local
