version: '2'
services:
#start These services can be disabled without affecting any other services
    webapp.dev: #s3mock service is given this name for easy internal excess
        image: rasodu/s3mock:dev
        ports:
            - "4569:4569"
    smtp:
        image: michielbdejong/mailtrap
        expose:
            - "25"
    dynamodb:
        image: deangiberson/aws-dynamodb-local
        expose:
            - "8000"
        ports:
            - "8000:8000"
#end These services can be disabled without affecting any other services
    phpfpm:
        volumes:
            - .:/usr/share/nginx/WEBAPP
    httpbackend:
        ports:
            - "80:80"
    cmd:
        image: rasodu/cmdlaravel:dev
        ports:
            - "3002:3000"
            - "3001:3001"
        volumes_from:
            - phpfpm
    nodejs:
        ports:
            - "8081:8080"
        volumes:
            - ./nodejs:/usr/src/app/
