version: '2'
services:
#start These services can be disabled without affecting any other services
    pusher:
        image: rasodu/pusherlaravel:dev
        depends_on:
            - redis
        expose:
            - "7001"
    broadcaster:
        image: rasodu/broadcasterlaravelechoserver:dev
        depends_on:
            - redis
        expose:
            - "6001"
    worker:
        image: rasodu/phpfpmlaravel:dev
        depends_on:
            - beanstalkd
            - phpfpm
        command: php artisan queue:listen --queue=high,default,low --timeout=60 --sleep=5 --tries=3
        volumes_from:
            - phpfpm
#end These services can be disabled without affecting any other services
    phpfpm:
        image: rasodu/phpfpmlaravel:dev
    https:
        image: rasodu/httpsnginx:dev
    httpbackend:
        image: rasodu/httpbackendlaravelnginx:dev
