version: '2'
services:
#start These services can be disabled without affecting any other services
    cron:
        image: rasodu/cron:dev
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
    elasticsearch:
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
    beanstalkd:
        volumes:
            - data-beanstalkd:/var/lib/beanstalkd
    redis:
        volumes:
            - data-redis:/data
#end These services can be disabled without affecting any other services
    http:
        image: rasodu/httpnginx:dev
        ports:
            - "80:80"
        volumes:
            - acme-challenge:/DLEMP/certbot/public/.well-known/acme-challenge
    certbot:
        image: rasodu/certbot:dev
        depends_on:
            - https
        volumes_from:
            - http:rw
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
            - var-lib-letsencrypt:/var/lib/letsencrypt
volumes:
    var-lib-mysql:
        driver: local
    elasticsearch-data:
        driver: local
    acme-challenge:
        driver: local
    data-beanstalkd:
        driver: local
    data-redis:
        driver: local
    var-lib-letsencrypt:
        driver: local
