version: '2'
services:
#start These services can be disabled without affecting any other services
    cron:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cron
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
    elasticsearch:
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
    beanstalkd:
        command: beanstalkd -p 11300 -u nobody -b /var/lib/beanstalkd
        volumes:
            - data-beanstalkd:/var/lib/beanstalkd
#end These services can be disabled without affecting any other services
    nginxhttp:
        volumes:
            - acme-challenge:/DLEMP/letsencrypt/public/.well-known/acme-challenge
    letsencrypt:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/letsencrypt
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        depends_on:
            - nginxhttps
        volumes_from:
            - nginxhttp:rw
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
volumes:
    var-lib-mysql:
        driver: local
    elasticsearch-data:
        driver: local
    acme-challenge:
        driver: local
    data-beanstalkd:
        driver: local
