version: '2'
services:
#start These services can be disabled without affecting any other services
    memcached:
        image: memcached:1.4.27-alpine
        expose:
            - "11211"
        command: memcached -p 11211 -m 64
    mysql:
        image: mysql:5.6.28
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
    elasticsearch:
        image: elasticsearch:2.4.1
        expose:
            - "9200"
        ports:
            - "9200:9200"
#end These services can be disabled without affecting any other services
#start Disabling these services require that you also disable services that depends on the services that you are disabling.
    beanstalkd: #Also turn off: workerlaravel
        image: rasodu/beanstalkd:v1.10.1
        command: beanstalkd -p 11300 -u nobody -b /var/lib/beanstalkd
        expose:
            - "11300"
    redis: #Also turn off: pusher
        image: redis:3.2.1-alpine
        command: redis-server --appendonly yes
        expose:
            - "6379"
#end Disabling these services require that you also disable services that depends on the services that you are disabling.
    phpfpm:
        build:
            context: .
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
                DLEMP_PHP_VERSION: ${DLEMP_PHP_VERSION}
        image: dlemp/phpfpm
        expose:
            - "9000"
    httpbackend:
        volumes_from:
            - phpfpm:ro
        depends_on:
            - phpfpm
        expose:
            - "80"
    nodejs:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/6nodejs
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        expose:
            - "8080"
    https:
        build:
            context: .
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        depends_on:
            - httpbackend
        ports:
            - "443:443"
            - "8080:8080"
            - "6001:6001"
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
volumes:
    etc-letsencrypt:
        driver: local
networks:
    default:
        driver: bridge
