version: '2'
services:
    phpfpm:
        build:
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/${DLEMP_PHP_VERSION}phpfpmdevlaravel
    pusher:
        ports:
            - "7000:7001"
    broadcaster:
        ports:
            - "6000:6001"
