version: '2'
services:
    nginxhttp:
        build:
            context: .
            dockerfile: docker/dockerfile/nginxhttp
        ports:
            - "80:80"
        volumes:
            - letsencrypt-live:/etc/letsencrypt/live
    memcached:
        image: memcached:1.4.25
        expose:
            - "11211"
        command: memcached -p 11211 -m 64
    mysql:
        image: mysql:5.6.28
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
    phpfpm:
        build:
            context: .
            dockerfile: docker/dockerfile/phpfpm
        expose:
            - "9000"
    nginxhttps:
        build:
            context: .
            dockerfile: docker/dockerfile/nginxhttps
        volumes_from:
            - nginxhttp:ro
            - phpfpm:ro
        ports:
            - "443:443"
volumes:
    letsencrypt-live:
        driver: local
networks:
    default:
        driver: bridge
