version: '2'
services:
#start These services can be disabled without affecting any other services
    webapp.dev: #s3mock service is given this name for easy internal excess
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/s3mock
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        ports:
            - "4569:4569"
    smtp:
        image: michielbdejong/mailtrap
        expose:
            - "25"
#end These services can be disabled without affecting any other services
    phpfpm:
        build:
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/phpfpmdev
        image: dlemp/phpfpm
        volumes:
            - .:/usr/share/nginx/WEBAPP
    cmd:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cmd
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes_from:
            - phpfpm
