version: '2'
services:
    smtp:
        image: michielbdejong/mailtrap
        expose:
            - "25"
    phpfpm:
        volumes:
            - .:/usr/share/nginx/WEBAPP
            - ./${DLEMP_BASE_DIR}docker/docker-config/php.ini-development-delta:/usr/local/etc/php/conf.d/development.ini
    cmd:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cmd
        volumes_from:
            - phpfpm
