memcached:
    image: memcached:1.4.25
    expose:
        - "11211"
    command: memcached -p 11211 -m 64
phpfpm:
    build: .
    dockerfile: dlemp-phpfpm
    expose:
        - "9000"
    links:
        - memcached
nginx:
    build: .
    dockerfile: dlemp-nginx
    ports:
        - "8080:80"
    links:
        - phpfpm
