version: '2'
services:
    phpfpm:
        volumes:
            - storage-app:/usr/share/nginx/WEBAPP/storage/app
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
    cron:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cron
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        volumes:
            - /usr/local/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    storage-app:
        driver: local
    var-lib-mysql:
        driver: local
