phpfpm:
    volumes:
        - storage-app:/usr/share/nginx/WEBAPP/storage/app
mysql:
    volumes:
        - var-lib-mysql:/var/lib/mysql
cron:
    build: .
    dockerfile: docker-cron
    volumes:
        - /usr/local/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
