version: '2'
services:
#start These services can be disabled without affecting any other services
    cron:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/cron
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
#end These services can be disabled without affecting any other services
    phpfpm:
        volumes:
            - storage-app:/usr/share/nginx/WEBAPP/storage/app
    nginxhttp:
        volumes:
            - acme-challenge:/DLEMP/letsencrypt/public/.well-known/acme-challenge
    letsencrypt:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/letsencrypt
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        depends_on:
            - nginxhttps
        volumes_from:
            - nginxhttp:rw
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
volumes:
    storage-app:
        driver: local
    var-lib-mysql:
        driver: local
    acme-challenge:
        driver: local
