version: '2'
services:
#start These services can be disabled without affecting any other services
    beanstalkd:
        image: michaelcontento/beanstalkd
        expose:
            - "11300"
    memcached:
        image: memcached:1.4.25
        expose:
            - "11211"
        command: memcached -p 11211 -m 64
    mysql:
        image: mysql:5.6.28
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
    nodesocket:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nodesocket
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        volumes_from:
            - nginxhttp:ro
        expose:
            - "3000"
        ports:
            - "3000:3000"
#end These services can be disabled without affecting any other services
#start Disabling these services require that you also disable services that depends on the services that you are disabling.
    redis: #Also turn off: nodesocket
        image: redis:3.0.7
        expose:
            - "6379"
#end Disabling these services require that you also disable services that depends on the services that you are disabling.
    phpfpm:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/phpfpm
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        expose:
            - "9000"
    nginxhttps:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nginxhttps
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        volumes_from:
            - nginxhttp:ro
            - phpfpm:ro
        ports:
            - "443:443"
    nginxhttp:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nginxhttp
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        ports:
            - "80:80"
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
volumes:
    etc-letsencrypt:
        driver: local
networks:
    default:
        driver: bridge
