version: '2'
services:
#start These services can be disabled without affecting any other services
    memcached:
        image: memcached:1.4.27-alpine
        expose:
            - "11211"
        command: memcached -p 11211 -m 64
    mysql:
        image: mysql:5.6.28
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
    pusherlaravel:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/pusherlaravel
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        depends_on:
            - nginxhttps
            - redis
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
        ports:
            - "3000:3000"
    queue:
        extends:
            service: phpfpm
        depends_on:
            - beanstalkd
        command: php artisan queue:listen --queue=high,default,low --timeout=60 --sleep=5 --tries=3
        volumes_from:
            - phpfpm
#end These services can be disabled without affecting any other services
#start Disabling these services require that you also disable services that depends on the services that you are disabling.
    beanstalkd: #Also turn off: queue
        image: kusmierz/beanstalkd:v1.10.0
        expose:
            - "11300"
    redis: #Also turn off: pusherlaravel
        image: redis:3.2.1-alpine
        expose:
            - "6379"
#end Disabling these services require that you also disable services that depends on the services that you are disabling.
    phpfpm:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/${DLEMP_PHP_VERSION}phpfpm
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
                DLEMP_PHP_VERSION: ${DLEMP_PHP_VERSION}
        expose:
            - "9000"
    nginxhttps:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nginxhttps
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        volumes_from:
            - phpfpm:ro
        ports:
            - "443:443"
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
    nginxhttp:
        build:
            context: .
            dockerfile: ${DLEMP_BASE_DIR}docker/dockerfile/nginxhttp
            args:
                DLEMP_BASE_DIR: ${DLEMP_BASE_DIR}
        ports:
            - "80:80"
volumes:
    etc-letsencrypt:
        driver: local
networks:
    default:
        driver: bridge
